#9 Remove Vaadin
cloud-erp-school-system/backend pull request #10
Opened 2021-03-09 18:44 UTC by Aurrix

@patricksan  Can you review this one?

2021-03-09 18:46 UTC, Aurrix commented
I updated dependencies and switched back to java 11.

2021-03-09 19:10 UTC, patricksan commented
@Aurrix There is just one remark. After that you can direct merge to master.
One important action, let's merge using `Squash and Merge`.

2021-03-09 19:10 UTC, patricksan requested changes

2021-03-09 19:10 UTC, patricksan commented on src/main/java/org/erp/school/config/SecurityConfiguration.java
>              .loginPage(LOGIN_URL).permitAll()
We can delete all the `LOGIN_*`.
I would also set the security configuration as permitAll() because we will not have anything over user until we investigate the POC Keycloack.

2021-03-09 20:43 UTC, Aurrix commented on src/main/java/org/erp/school/config/SecurityConfiguration.java
>              .loginPage(LOGIN_URL).permitAll()
I have permitted all requests for now. I have a feeling the entire security config will be removed or changed. But I suggest this be done for a story related to the Keycloack integration.

2021-03-09 20:44 UTC, Aurrix commented
@patricksan Do you know why the maven build fails with Travis?  It builds ok locally. I am thinking maybe it's due to me switching to java 11?

2021-03-10 06:54 UTC, patricksan commented
We can remove with the issue of Keycloack. 

One thing we need to validate is the code format you are using. Are you using IntelliJ IDEA? Otherwise it shows that you changed the code but in reality was just formatting the file. 

Related to the build fail, it is not just the jdk11 but also a profile from vaadin that was removed.  I already fix in the master. So you can merge. 

Thanks

2021-03-10 07:18 UTC, merged